package main

import (
	"io"
	"strings"

	. "github.com/davelondon/jennifer/jen"
)

// Render the file
func Render(w io.Writer) error {
	file := NewFile("jen")

	file.Comment("\tThis file is generated by genjen - do not edit!\n")
	file.Line()

	for _, b := range Groups {
		b := b // b used in closures
		if b.Name == "" {
			continue
		}
		comment := Commentf("%s %s", b.Name, b.Desc)

		if b.Variadic && len(b.Parameters) > 1 {
			panic("should not have variadic function with multiple params")
		}

		var variadic Code
		if b.Variadic {
			variadic = Op("...")
		}
		var funcParams []Code
		var callParams []Code
		for _, name := range b.Parameters {
			funcParams = append(funcParams, Id(name).Add(variadic).Id("Code"))
			callParams = append(callParams, Id(name).Add(variadic))
		}

		addFunctionAndGroupMethod(
			file,
			b.Name,
			comment,
			funcParams,
			callParams,
		)

		/*
			// {comment}
			func (s *Statement) {Name}({funcParams}) *Statement {
				g := &Group{
					items:     []Code{{ParamNames...}}|{ParamName[0]},
					open:      "{Open}",
					close:     "{Close}",
					separator: "{Separator}",
				}
				*s = append(*s, g)
				return s
			}
		*/
		file.Add(comment)
		file.Func().Params(
			Id("s").Op("*").Id("Statement"),
		).Id(b.Name).Params(
			funcParams...,
		).Op("*").Id("Statement").Block(
			Id("g").Op(":=").Op("&").Id("Group").Dict(map[Code]Code{
				Id("items"): Do(func(s *Statement) {
					if b.Variadic {
						s.Id(b.Parameters[0])
					} else {
						s.Index().Id("Code").ValuesFunc(func(g *Group) {
							for _, name := range b.Parameters {
								g.Id(name)
							}
						})
					}
				}),
				Id("open"):      Lit(b.Open),
				Id("close"):     Lit(b.Close),
				Id("separator"): Lit(b.Separator),
			}),
			Op("*").Id("s").Op("=").Append(Op("*").Id("s"), Id("g")),
			Return(Id("s")),
		)

		funcComment := Commentf("%sFunc %s", b.Name, b.Desc)
		funcFuncParams := []Code{Id("f").Func().Params(Op("*").Id("Group"))}
		funcCallParams := []Code{Id("f")}

		if b.Variadic && !b.PreventFunc {
			funcName := b.Name + "Func"
			addFunctionAndGroupMethod(
				file,
				funcName,
				funcComment,
				funcFuncParams,
				funcCallParams,
			)

			/*
				// {comment}
				func (s *Statement) {NameFunc}(f func(*Group)) *Statement {
					g := &Group{
						open:      "{Open}",
						close:     "{Close}",
						separator: "{Separator}",
					}
					f(g)
					*s = append(*s, g)
					return s
				}
			*/
			file.Add(funcComment)
			file.Func().Params(
				Id("s").Op("*").Id("Statement"),
			).Id(funcName).Params(
				funcFuncParams...,
			).Op("*").Id("Statement").Block(
				Id("g").Op(":=").Op("&").Id("Group").Dict(map[Code]Code{
					Id("open"):      Lit(b.Open),
					Id("close"):     Lit(b.Close),
					Id("separator"): Lit(b.Separator),
				}),
				Id("f").Call(Id("g")),
				Op("*").Id("s").Op("=").Append(Op("*").Id("s"), Id("g")),
				Return(Id("s")),
			)
		}
	}

	type tkn struct {
		name      string
		cap       string
		tokenType string
		tokenDesc string
	}
	tokens := []tkn{}
	for _, v := range Identifiers {
		tokens = append(tokens, tkn{
			name:      v,
			cap:       strings.ToUpper(v[:1]) + v[1:],
			tokenType: "identifierToken",
			tokenDesc: "identifier",
		})
	}
	for _, v := range Keywords {
		tokens = append(tokens, tkn{
			name:      v,
			cap:       strings.ToUpper(v[:1]) + v[1:],
			tokenType: "keywordToken",
			tokenDesc: "keyword",
		})
	}

	for _, t := range tokens {
		t := t // used in closures
		comment := Commentf(
			"%s renders the %s %s.",
			t.cap,
			t.name,
			t.tokenDesc,
		)
		addFunctionAndGroupMethod(
			file,
			t.cap,
			comment,
			nil,
			nil,
		)

		/*
			// {comment}
			func (s *Statement) {Name}() *Statement {
				t := token{
					typ:     {identifierToken|keywordToken},
					content: "{Name}",
				}
				*s = append(*s, t)
				return s
			}
		*/
		file.Add(comment)
		file.Func().Params(
			Id("s").Op("*").Id("Statement"),
		).Id(t.cap).Params().Op("*").Id("Statement").Block(
			Id("t").Op(":=").Id("token").Dict(map[Code]Code{
				Id("typ"):     Id(t.tokenType),
				Id("content"): Lit(t.name),
			}),
			Op("*").Id("s").Op("=").Append(Op("*").Id("s"), Id("t")),
			Return(Id("s")),
		)
	}

	return file.Render(w)
}

// For each method on *Statement, this this generates a package level
// function and a method on *Group, both with the same name.
func addFunctionAndGroupMethod(
	file *File,
	name string,
	comment *Statement,
	funcParams []Code,
	callParams []Code,
) {
	/*
		// {comment}
		func {name}({params}) *Statement {
			return newStatement().{name}({call})
		}
	*/
	file.Add(comment)
	file.Func().Id(name).Params(funcParams...).Op("*").Id("Statement").Block(
		Return(
			Sel(
				Id("newStatement").Call(),
				Id(name).Call(callParams...),
			),
		),
	)
	/*
		// {comment}
		func (g *Group) {name}({params}) *Statement {
			s := {name}({call})
			g.items = append(g.items, s)
			return s
		}
	*/
	file.Add(comment)
	file.Func().Params(
		Id("g").Op("*").Id("Group"),
	).Id(name).Params(funcParams...).Op("*").Id("Statement").Block(
		Id("s").Op(":=").Id(name).Params(callParams...),
		Sel(Id("g"), Id("items")).Op("=").Append(Sel(Id("g"), Id("items")), Id("s")),
		Return(Id("s")),
	)
}
